docs: Add selected/disabled states to useCheckboxGroupItem example
adobe/react-spectrum pull request #1336
Opened 2020-12-02 12:10 UTC by stefanprobst

Closes #1302

Shows getting `selected` and `disabled` states for checkboxgroup item (which is different from standalone checkbox) in docs example. Also adds missing `ref`.

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [x] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

## 🧢 Your Project:

2020-12-02 17:22 UTC, snowystinger submitted a review, later dismissed
Looks good to me!

2020-12-07 23:48 UTC, dannify requested changes
Thanks for helping improve our docs. Just a color suggestion help with accessibility otherwise it looks good.

2020-12-07 23:48 UTC, dannify commented on packages/@react-aria/checkbox/docs/useCheckboxGroup.mdx
> +        color: (isDisabled && 'slategray') || (isSelected && 'royalblue'),
Let's make sure these colors are accessible. We have some basic color vars to use in examples like this.
```suggestion
        color: (isDisabled && 'var(--gray)') || (isSelected && 'var(--blue)',
```

2020-12-08 18:28 UTC, dannify approved these changes

2020-12-08 20:06 UTC, merged