explicitly defining slider closest thumb support for splitting on zero
adobe/react-spectrum pull request #1403
Opened 2020-12-18 23:47 UTC by ktabors

followup PR https://github.com/adobe/react-spectrum/pull/1393 to improving handling of stack thumbs

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

click to the left of slider thumbs

## 🧢 Your Project:
RSP

2020-12-18 23:57 UTC, dannify requested changes

2020-12-18 23:57 UTC, dannify commented on packages/@react-aria/slider/src/useSlider.ts
> +      // Confirm that the found closedt thumb is editable, not disabled, and move it
```suggestion
      // Confirm that the found closest thumb is editable, not disabled, and move it
```

2020-12-19 00:14 UTC, devongovett approved these changes

2020-12-19 00:17 UTC, LFDanLu approved these changes

2020-12-19 00:20 UTC, merged