fix - useOverlayPosition mount flicker
adobe/react-spectrum pull request #1695
Opened 2021-03-12 16:26 UTC by intergalacticspacehighway

Closes 

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues/1694).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:
One can check this [storybook example](http://localhost:9003/?path=/story/useoverlayposition--positioned-container-bottom). 
Sometimes after reload clicking on trigger leads to flicker. Note - Only happens on first mount as new position gets stored and it's used in re-renders.

## 🧢 Your Project:
GeekyAnts

2021-03-12 23:39 UTC, LFDanLu requested changes

2021-03-12 23:39 UTC, LFDanLu commented on packages/@react-aria/overlays/src/useOverlayPosition.ts
> +import {HTMLAttributes, RefObject, useCallback, useLayoutEffect, useRef, useState} from 'react';
Looks like the SSR tests are failing, think you can use `useLayoutEffect` from the react-aria package to fix

2021-03-15 19:23 UTC, LFDanLu reviewed
Looks like this breaks `MenuTrigger` menu rendering. I was able to fix it locally by updating `MenuTrigger` so that it has a similar useLayoutEffect as Picker, but I need to dig some more to see if this is the appropriate fix

2021-03-19 00:28 UTC, LFDanLu commented
@intergalacticspacehighway Just an update, got a little bit of time to look and a possible alternate fix to the MenuTrigger problem is to change the following useEffects to useLayoutEffects: 
https://github.com/adobe/react-spectrum/blob/main/packages/@react-aria/interactions/src/usePress.ts#L75
https://github.com/adobe/react-spectrum/blob/main/packages/@react-spectrum/menu/src/Menu.tsx#L37-L44

Now that useOverlayPosition uses `useLayoutEffect`, we need to sync the refs that get provided by the context providers during the same phase otherwise useOverlayPosition can't calculate the proper position. Haven't tested this too thoroughly, not sure if it would break anything else, will hopefully get some more time next week to look

2021-04-05 23:40 UTC, LFDanLu commented
@intergalacticspacehighway Sorry about the delay, got some time today to test the changes I mentioned before. It doesn't look like they break anything, gonna push those changes to your branch and get another set of eyes to take a look.

2021-04-07 19:56 UTC, snowystinger approved these changes
I tested in the useOverlayPosition stories, it has gotten rid of the flicker. I'm not seeing any issues with autofocus, grid focus movement, or menus (quick things to check). We'll have to make a good pass of this in our testing session, the change is subtle.

2021-04-19 23:34 UTC, devongovett approved these changes

2021-04-19 23:34 UTC, merged