Improve initial drop target in collections when keyboard dragging
adobe/react-spectrum pull request #1735
Opened 2021-03-23 16:05 UTC by devongovett

This changes the logic used to select the initial drop target within a collection when keyboard dragging. Previously, the initial drop target was the collection root if supported, or before the first item. This meant that if you were trying to insert into a very long list, you'd be taken to the top first and need to press the down arrow many times to get to the item you want to drop on. Similarly, when reordering a list, you'd select some items to move, and the insertion point would move all the way to the top of the list rather than being able to easily move by one from the initial location.

This changes the behavior so that:

* The initial drop target is after the previously focused item. This means you can scroll the list to where you want by navigating with the keyboard, and when dropping there, it will retain your position rather than starting from the top.
* If there is no focused item, then the initial drop target is the root, as before.
* The above rules change slightly when there is a selection, which I felt improved things when reordering multiple items in a list. 
  * If the last focused key is also the first selected key, then the initial drop target is before the first selected key. This way, if you select multiple items from bottom to top, we assume you want to move the items upward in the list, so the insertion point is placed before your selection.
  * Otherwise, if the last focused key is selected, then the initial drop target is after the last selected key. This way, if you select from top to bottom, the insertion point is placed after your selection.

Still need to write tests for this behavior, but wanted to get feedback on these proposed interactions.

2021-03-23 16:35 UTC, snowystinger commented
Tried each of them out, it definitely feels like an improvement over before.
In long lists I think it's preferable to do it this way because you can always use the home key to get to the root if that's actually what you intended. It reduces the amount of automatic scrolling that happens too, and I think that's a good thing.

2021-03-23 21:49 UTC, majornista commented
I agree with @snowystinger this behavior is a big improvement.

2021-03-24 23:22 UTC, devongovett commented
Thanks for taking a look. Added tests. 😄

2021-03-25 17:43 UTC, snowystinger approved these changes
looks good, tiny bit to make tests more readable, but otherwise looks good

2021-03-25 17:43 UTC, snowystinger commented on packages/@react-aria/dnd/test/useDroppableCollection.test.js
> +    it('should default to on the last selected item there is a selection and only dropping on items is allowed', () => {
english is a little hard to parse
maybe
```suggestion
it('should default to `on` the last selected item in the selection if only dropping on items is allowed', () => {
```

2021-03-25 17:44 UTC, snowystinger requested changes
fix 17 tests :)

2021-03-25 21:28 UTC, snowystinger approved these changes

2021-03-30 22:27 UTC, LFDanLu approved these changes
LGTM. I did have one thought: what do you think about updating the drop target's focused key when the user is cycling through the options while in dragging mode? I felt that it was kinda odd that a user could scroll through the list options, drop their drag target somewhere, but then when tabbing back to the drop target the list scroll back to the initial entry point rather than keeping the scroll position as is.

To reproduce:
1.  Go to drag-and-drop--droppable-grid-with-many-items story
2. Tab to the right list (drop list) and arrow down so "Item 1" is focused
3. Tab to left list and begin keyboard dragging on any of the items
4. Scroll down the right list and drop the item below "Item 13". The view should not scroll after the drop
5. Tab to the right list again. The view should jump back to "Item 1"

Still digging locally to see if this is a simple story change or something to do with the selectionManager 

EDIT: perhaps setting selectionManager.focusedKey in onDropTargetEnter?

2021-04-01 16:44 UTC, devongovett commented
@LFDanLu I think #1721 is what you're looking for?

2021-04-01 17:32 UTC, LFDanLu commented
@devongovett Partially yes, but there is still the case where the user might scroll through the droppable collection while in dragging mode but then cancel the drag operation (not as common a scenario admittedly, but perhaps the user realizes that they selected the wrong item to drag). In #1721 the focusedKey for the droppable collection wouldn't be updated and tabbing back into the droppable collection would cause the jump in scroll position.

2021-04-01 20:28 UTC, devongovett commented
I suppose, but I guess that's normally the case with scrolling anyway? Like if you just used the scroll wheel to browse through items, that doesn't affect the focused item. If you tabbed in afterward, it would jump the scroll position back to the last focused item too.

2021-04-08 17:45 UTC, dannify approved these changes

2021-04-08 17:45 UTC, merged