Add shouldUseVirtualFocus to AriaListBoxOptions interface (#1635)
adobe/react-spectrum pull request #2017
Opened 2021-06-14 16:52 UTC by reidbarber

Closes #1635 

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

1. Pass shouldUseVirtualFocus into useListBox
2. Verify that there is no typescript warning (i.e. "Object literal may only specify known properties, and 'shouldUseVirtualFocus' does not exist in type 'AriaListBoxOptions'")

## 🧢 Your Project:

2021-06-14 17:28 UTC, LFDanLu requested changes

2021-06-14 17:29 UTC, reidbarber commented on packages/@react-aria/listbox/src/useListBox.ts
> +   * Whether the collection items should use virtual focus instead of being focused directly.
Good catch, that makes sense.

2021-06-14 17:40 UTC, LFDanLu approved these changes
LGTM

2021-06-23 22:30 UTC, snowystinger approved these changes
lgtm

2021-06-25 21:05 UTC, merged