Update useListData to handle select all w/ unloaded lists
adobe/react-spectrum pull request #2225
Opened 2021-08-17 02:29 UTC by jluyau

If list data has unloaded items, removing the last visible selected item will keep the selection at the `all` value. If all items have been loaded, removing the last visible selected item will change selection to an empty set.

If list data has unloaded items, a remove `all` selected items will remain at the `all` value. If all items have been loaded, a remove `all` will change selection to an empty set.

2021-08-18 16:44 UTC, devongovett commented on packages/@react-stately/data/src/useListData.ts
> +            selectedKeys: cursor != null ? 'all' : new Set()
Wouldn't the previous behavior make sense here though? If `all` was previously selected, and those items were removed, then that means that all items, even those not yet loaded have been deleted.

2021-08-18 16:46 UTC, devongovett commented on packages/@react-stately/data/src/useListData.ts
> +        if (cursor == null && items.length === 0) {
Should we add a test for this case?

2021-08-19 00:21 UTC, LFDanLu requested changes
Just a small nit, but otherwise LGTM

2021-08-19 00:21 UTC, LFDanLu commented on packages/@react-stately/data/src/useListData.ts
> +          // return 'all' value if there still exists unloaded items (i.e. cursor is not null)
nit: remove this comment

2021-08-20 01:33 UTC, devongovett approved these changes

2021-08-20 01:44 UTC, dannify approved these changes

2021-08-20 01:44 UTC, merged