Allow custom messages on DismissButton
adobe/react-spectrum pull request #2868
Opened 2022-02-17 19:15 UTC by snowystinger

Closes https://github.com/adobe/react-spectrum/issues/2866

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

## 🧢 Your Project:

2022-02-17 19:37 UTC, LFDanLu requested changes
small nit, but otherwise looks good

2022-02-17 19:37 UTC, LFDanLu commented on packages/@react-aria/overlays/test/DismissButton.test.tsx
> +  it('should accept an aria-labelledby', function () {
Nit:
```suggestion
  it('should accept an aria-labelledby and aria-label', function () {
```

2022-02-18 20:52 UTC, devongovett approved these changes

2022-02-18 21:26 UTC, LFDanLu approved these changes
LGTM

2022-02-18 21:47 UTC, merged