Allow entering era in date picker by typing
adobe/react-spectrum pull request #3208
Opened 2022-06-09 15:40 UTC by devongovett

Depends on #3167.

This adds support for entering an era in DatePicker by typing the first letter. This enables users of mobile devices to select an era when up and down arrow keys are not available.

2022-06-09 18:42 UTC, LFDanLu requested changes
Just one error I noticed but otherwise confirmed that I can type for Japanese eras on Android and desktop. I don't see a era segment for the Ethiopic calendar though, is there supposed to be one?

2022-06-10 00:14 UTC, devongovett commented
Yeah the focus issue is a known issue (came up in testing), which I will fix separately.

The way you found is the only way to enter a BC date. I don't figure it's super common so no need to display AD all the time IMO. Could add an option for it in the future if we had to for some reason.

2022-06-10 00:38 UTC, devongovett commented on packages/@react-aria/datepicker/src/useDateSegment.ts
> +      let formatted = parts.find(p => p.type === 'era').value;
Good catch. Fixed it. Seems like the era wasn't returned if the year was also omitted.

Also noticed that we were forcing a long era name in calendar for all non-gregorian calendars, so got rid of that. The era is shown automatically by the formatter only when needed.

2022-06-10 00:44 UTC, snowystinger approved these changes

2022-06-10 15:37 UTC, majornista requested changes
As with ArrowUp/ArrowDown to change era, we need to manage focus when changing the era removes the focused segment from the DateField. With Gregorian calendar, typing `A` with focus on `BC` will select the common era, but remove the segment causing focus to be lost.

2022-06-10 16:20 UTC, devongovett commented
@majornista that should be solved by #3213 once both PRs are merged together.

2022-06-10 16:43 UTC, majornista approved these changes

2022-06-10 17:30 UTC, LFDanLu approved these changes
looks good to me for the most part, verified the other issues are now resolved. Just one thing I noticed with the Ethiopic era: once you select/confirm a date the era set is no longer changeable. Maybe something specific to how Ethiopic calendars work? Trying to dig into this, but not a blocker for this PR since this seems to be pre-existing behavior

2022-06-10 17:44 UTC, devongovett commented
@LFDanLu interesting. I'll look at that separately. I think it's due to some weirdness with the Ethiopic calendar. The eras don't really work like in other calendars where there is a single timeline. Instead, they are two different reference points on the same timeline. Essentially, AA 5501 = AM 1. So when switching between eras I guess we need to also update the year field perhaps...

2022-06-10 17:47 UTC, merged