DatePicker blog post and docs updates
adobe/react-spectrum pull request #3233
Opened 2022-06-15 16:20 UTC by devongovett

For release.

2022-06-15 16:52 UTC, snowystinger commented on packages/dev/docs/pages/blog/datepicker.mdx
> +This approach has benefits for internationalization and accessibility, as well as usability on mobile. For internationalization, individual segments avoid the problem of parsing dates in various form
I'm going to assume you meant QWERTY ;P

2022-06-15 18:13 UTC, majornista requested changes

2022-06-15 18:13 UTC, majornista commented on packages/dev/docs/pages/blog/datepicker.mdx
> +Correctly manipulating dates and times in *really hard*. Making assumptions about calendar systems, time zones, locales, date and time arithmetic, etc. is a recipe for bugs when users around the worl
Correctly manipulating dates and times is *really hard*.

2022-06-15 18:13 UTC, majornista commented on packages/dev/docs/pages/blog/datepicker.mdx
> +Correctly manipulating dates and times in *really hard*. Making assumptions about calendar systems, time zones, locales, date and time arithmetic, etc. is a recipe for bugs when users around the worl
"is" not "in"

2022-06-15 18:20 UTC, snowystinger commented on packages/dev/docs/pages/blog/datepicker.mdx
> +Most developers are not aware of all of the minutiae of the different calendar systems. As a result, it’s easy to make assumptions in applications based on your own knowledge, which may lead to bugs
condescending tone, maybe consider changing to
```suggestion
It’s easy to make wrong assumptions in applications due to the complexity and subtle differences in calendar systems, which may lead to bugs for users in other parts of the world. To make this easier, the APIs for all of our date and time picker components handle all of the details and calendar conversions for you. If you provide a date in the Gregorian calendar system as a value to a component, that’s what you’ll get back, no matter which calendar system the user is interacting with. This allows applications to deal with dates from all users consistently, even if users enter dates in a different calendar system than they are stored in.
```

2022-06-15 19:32 UTC, devongovett commented on packages/dev/docs/pages/blog/datepicker.mdx
> +<Video src={calendarMobileScreenReader + '#t=0.1'} preload="metadata" controls style={{maxHeight: '600px', maxWidth: 'min(100%, 1920px)', display: 'block', margin: '40px auto'}} />
I did have the VO captions turned on, they appear at the bottom.

2022-06-16 03:18 UTC, majornista commented on packages/dev/docs/pages/blog/datepicker.mdx
> +<Video src={calendarMobileScreenReader + '#t=0.1'} preload="metadata" controls style={{maxHeight: '600px', maxWidth: 'min(100%, 1920px)', display: 'block', margin: '40px auto'}} />
Perhaps hard to see under video controls?

2022-06-16 03:28 UTC, devongovett commented on packages/dev/docs/pages/blog/datepicker.mdx
> +<Video src={calendarMobileScreenReader + '#t=0.1'} preload="metadata" controls style={{maxHeight: '600px', maxWidth: 'min(100%, 1920px)', display: 'block', margin: '40px auto'}} />
Updated to use the video you sent me with the captions. I tried to figure out how to use WebVTT captions but couldn't get it to work.

2022-06-16 03:29 UTC, devongovett commented on packages/dev/docs/pages/blog/datepicker.mdx
> +<Video src={datepickerVideo} muted loop autoPlay style={{maxWidth: 'min(100%, 1920px)', display: 'block', margin: '40px auto'}} />
Good idea! Made it not autoplay if that media query is true. Also made it possible to pause the autoplaying video even when the media query is not true.

2022-06-16 13:09 UTC, majornista commented on packages/dev/docs/pages/blog/datepicker.mdx
> +<Video src={datepickerVideo} muted loop autoPlay style={{maxWidth: 'min(100%, 1920px)', display: 'block', margin: '40px auto'}} />
Are there other autoPlay videos in blog posts that we could treat the same?

2022-06-16 17:24 UTC, devongovett commented on packages/dev/docs/pages/blog/datepicker.mdx
> +```
added to client.js so it applies to all pages automatically.

2022-06-16 19:19 UTC, majornista commented on packages/dev/docs/pages/blog/datepicker.mdx
> +Most developers are not aware of all of the minutiae of the different calendar systems. As a result, it’s easy to make assumptions in applications based on your own knowledge, which may lead to bugs
Nitpick. The last sentence ends with an unnecessary dangling preposition.
```suggestion
Most developers are not aware of all of the minutiae of the different calendar systems. As a result, it’s easy to make assumptions in applications based on your own knowledge, which may lead to bugs for users in other parts of the world. To make this easier, the APIs for all of our date and time picker components handle all of the details and calendar conversions for you. If you provide a date in the Gregorian calendar system as a value to a component, that’s what you’ll get back, no matter which calendar system the user is interacting with. This allows applications to deal with dates from all users consistently, even if users enter dates in a different calendar system than that in which they are stored.
```

2022-06-16 19:25 UTC, majornista commented on packages/dev/docs/pages/blog/date-and-time-pickers-for-all.mdx
> +It’s easy to make assumptions based on the calendar system you use every day and test with during development, which may lead to bugs when users in other parts of the world use your app. To make this
Nitpick. Last sentence in this paragraph ends with a dangling preposition.
```suggestion
It’s easy to make assumptions based on the calendar system you use every day and test with during development, which may lead to bugs when users in other parts of the world use your app. To make this easier, the APIs for all of our date and time picker components handle all of the details and calendar conversions for you. If you provide a date in the Gregorian calendar system as a value to a component, that’s what you’ll get back, no matter which calendar system the user is interacting with. This allows applications to deal with dates from all users consistently, even if users enter dates in a different calendar system than that in which they are stored.
```

2022-06-16 19:25 UTC, majornista submitted a review, later dismissed

2022-06-20 14:57 UTC, majornista submitted a review, later dismissed

2022-06-21 01:02 UTC, LFDanLu approved these changes
Small comments for things that I noticed when reading the post, but minor enough that I'm happy approving this. Super well polished, excited for this to go out!

2022-06-21 01:20 UTC, devongovett commented on packages/dev/docs/pages/blog/date-and-time-pickers-for-all.mdx
> +<Video
Yeah this one doesn't have `controls`. I felt it was less important than the others, as this is really just showing a looping demo reel where the others are demonstrating something specific.

2022-06-21 14:49 UTC, merged