Remove dom-helpers dependency from @react-aria/overlays
adobe/react-spectrum pull request #3291
Opened 2022-07-11 03:34 UTC by devongovett

Reduces bundle size by ~1.8 KB.

2022-07-11 15:27 UTC, reidbarber submitted a review, later dismissed

2022-07-11 20:27 UTC, LFDanLu requested changes

2022-07-11 20:27 UTC, LFDanLu commented on packages/@react-aria/overlays/src/calculatePosition.ts
> +}
This errors when I attempt to open a Picker in the following story: https://reactspectrum.blob.core.windows.net/reactspectrum/7c18f4284ae7f6fd19e8b8be8da8ee28e82cc2b4/storybook/index.html?path=/story/picker--default&providerSwitcher-toastPosition=bottom. Similar thing happens which other overlay components (MenuTrigger, ComboBox, etc)

2022-07-11 23:20 UTC, devongovett commented on yarn.lock
> +dom-helpers@^5.0.1:
Yes, react-spectrum will still have a dependency, but react-aria won't

2022-07-12 15:13 UTC, reidbarber approved these changes
LGTM, no crashes :)

2022-07-12 16:41 UTC, snowystinger approved these changes
looks good, more complicated examples such as offset/cross offset/different containers/different targets all seem to be working as expected

2022-07-12 17:10 UTC, LFDanLu approved these changes

2022-07-12 23:21 UTC, merged