fix(#3299): SearchAutocomplete/SearchWithin support icon prop override
adobe/react-spectrum pull request #3300
Opened 2022-07-12 20:28 UTC by majornista

Closes #3299 

## ✅ Pull Request Checklist:

- [x] Included link to corresponding React Spectrum GitHub Issue #3299 .
- [x] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [x] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

## 🧢 Your Project:

Adobe/Accessibility

2022-07-20 15:57 UTC, reidbarber requested changes
Looks great, tested on Chrome, FF, Safari, and iOS Safari.

One thing, I believe SearchWithin may be or has already been deprecated, so it might be better not to include the change in this. I'm not opposed to including it, but someone else may have an objection.

If you can add a chromatic story for each of these, I'm good to approve.

2022-07-22 16:16 UTC, reidbarber submitted a review, later dismissed

2022-08-03 23:41 UTC, devongovett approved these changes

2022-08-03 23:47 UTC, dannify approved these changes

2022-08-03 23:53 UTC, merged