TagGroup: Add docs for maxRows and onAction
adobe/react-spectrum pull request #3918
Opened 2023-01-13 17:18 UTC by reidbarber

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

## 🧢 Your Project:

2023-01-13 18:32 UTC, matthewdeutsch commented
<img width="730" alt="image" src="https://user-images.githubusercontent.com/700930/212393124-5587e27c-7911-4444-adec-e654b4d79176.png">
This action is firing when pressing (with mouse but not keyboard) on tag names as well, is that intended?

2023-01-13 18:34 UTC, reidbarber commented
@matthewdeutsch just handled this in #3893, just haven't pulled in those new changes to this branch yet.

2023-01-14 05:01 UTC, ktabors reviewed
Looks good.

The prop description for `maxRows` seems to be outside this PR, but seems off. This prop provides a button to toggle "limiting the rows of content" or "showing all possible tag content". The current description makes it sound like it's just a show more button.

Current: `Limit the number of rows initially shown. This will render a button that allows the user to expand to show all tags.`

The second sentence could be more like: `Renders a button to toggle showing all tags or tags limited by this prop.`

2023-01-19 21:27 UTC, LFDanLu reviewed
Docs look good to me, bit whats up with the additional translations in the aria package?

2023-01-19 21:59 UTC, reidbarber commented
> Docs look good to me, but whats up with the additional translations in the aria package?

Ahh thanks, that was left over from a merge.

2023-01-19 22:06 UTC, snowystinger reviewed
Initial review looks good, holding approval until we rename onAction

2023-01-19 22:06 UTC, snowystinger commented on packages/@react-spectrum/tag/docs/TagGroup.mdx
> +### onAction
Pending we rename this

2023-01-19 22:18 UTC, LFDanLu reviewed
Provisional approval as well

2023-02-22 11:38 UTC, dannify requested changes

2023-02-22 11:38 UTC, dannify commented on packages/@react-spectrum/tag/docs/TagGroup.mdx
> +        items={items}
Let's reduce the number of items in this example so that they don't take up so much space in the code (especially on mobile)

2023-02-22 16:41 UTC, devongovett commented on packages/@react-spectrum/tag/docs/TagGroup.mdx
> +<View maxWidth="size-3400" minHeight="size-3400" padding="size-150" borderWidth="thin" borderColor="dark" borderRadius="medium">
why is it so tall? :D

2023-02-22 17:36 UTC, devongovett approved these changes

2023-02-22 19:58 UTC, dannify approved these changes

2023-02-23 23:16 UTC, merged