TagGroup: add docs for help text, contextual help, and avatars
adobe/react-spectrum pull request #3964
Opened 2023-01-26 04:58 UTC by reidbarber

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

## 🧢 Your Project:

2023-01-26 20:24 UTC, ktabors submitted a review, later dismissed

2023-01-26 22:48 UTC, LFDanLu submitted a review, later dismissed
LGTM

2023-02-22 16:23 UTC, devongovett commented
Is it right that the label doesn't align with the first tag?

<img width="209" alt="image" src="https://user-images.githubusercontent.com/19409/220689957-65f935ed-c051-4423-a4d1-3e3877b40d28.png">

2023-02-22 16:24 UTC, devongovett commented
Also the label should not use a `<label>` element, because it isn't labeling an HTML form element. Should just be a `<span>`.

2023-02-22 16:27 UTC, devongovett commented on packages/@react-spectrum/tag/docs/TagGroup.mdx
> +    <Avatar src="https://i.imgur.com/kJOwAdv.png" alt="Person 1 avatar" />
I think these avatars should not have alt text (it defaults to "" in the Avatar component). Right now tags are read by screen readers as "Person 1 avatar Person 1", which is kinda unnecessarily verbose. The avatar is essentially decorative so I don't think it needs its own alt text.

2023-02-22 16:35 UTC, reidbarber commented
> Is it right that the label doesn't align with the first tag?

I agree, it does look weird. I can fix by changing the margin from 4px on each side, to 8px on end.

2023-02-22 16:39 UTC, devongovett commented
Or maybe the tags shouldn't have margins and we could use gap instead? Then the first/last tag wouldn't have a margin.

2023-02-22 17:25 UTC, reidbarber commented
@devongovett We're using `display: inline` on the tags so that the actions can be on the same line, while being outside of the tag group. Gap only applies to flex, grid, and columns. Looking into a way to do both.

2023-02-22 17:35 UTC, devongovett commented
Can you use `inline-flex` with `flex-wrap`?

2023-02-22 17:37 UTC, reidbarber commented
Looks like that might work if I also make the actions inline-flex. Double checking for any side effects.

2023-02-22 19:56 UTC, reidbarber commented
Pushed a fix in https://github.com/adobe/react-spectrum/pull/4102

2023-02-22 21:59 UTC, devongovett commented
FYI looks like the example in the "Content" section overflows horizontally on mobile causing page scrolling.

2023-02-22 22:21 UTC, reidbarber commented
@devongovett I can remove the Flex's used in these; don't think they're adding much.

Should I replace the Adobe products tags with News, Shopping, etc? May be closer to real life use case and have more realistic width for wrapping on mobile.

2023-02-22 22:33 UTC, devongovett commented
Sure 🤷

2023-02-23 00:31 UTC, devongovett approved these changes

2023-02-23 01:09 UTC, LFDanLu requested changes

2023-02-23 01:09 UTC, LFDanLu commented on packages/@react-spectrum/tag/docs/TagGroup.mdx
> +  let isValid = items.length <= 8;
```suggestion
  let isValid = items.length <= 3;
```

2023-02-23 01:36 UTC, LFDanLu approved these changes

2023-02-23 23:56 UTC, dannify approved these changes

2023-02-23 23:57 UTC, devongovett approved these changes

2023-02-23 23:59 UTC, merged