Add TagGroup component to RAC
adobe/react-spectrum pull request #4661
Opened 2023-06-14 06:57 UTC by devongovett

This adds `TagGroup` to React Aria Components. The API looks like this:

```jsx
<TagGroup selectionMode="multiple">
  <Label>Categories</Label>
  <TagList>
    <Tag>News</Tag>
    <Tag>Travel</Tag>
    <Tag>Gaming</Tag>
    <Tag>Shopping</Tag>
  </TagList>
</TagGroup>
```

We use a separate `Tag` component rather than `Item` here due to the additional `allowsRemoving` render prop. A remove button can be added with `<Button slot="remove">` (slot prop just in case there are other buttons).

2023-06-14 06:59 UTC, devongovett commented on packages/@react-aria/tag/src/useTagGroup.ts
> +  });
Bug fix. I noticed we were getting a `for` attribute on the label that's rendered as a span, which is invalid html.

2023-06-14 21:35 UTC, reidbarber submitted a review, later dismissed

2023-06-14 21:35 UTC, reidbarber commented on packages/react-aria-components/docs/TagGroup.mdx
> +An `<Tag>` defines a single item within a `<TagList>`.
```suggestion
A `<Tag>` defines a single item within a `<TagList>`.
```

2023-06-14 22:09 UTC, snowystinger approved these changes

2023-06-14 22:11 UTC, LFDanLu requested changes
just one accessibility issue I noticed, we should test further on Monday in case there are other instances

2023-06-14 22:11 UTC, LFDanLu commented on packages/react-aria-components/src/TagGroup.tsx
> +  let {rowProps, gridCellProps, removeButtonProps, ...states} = useTag({item}, state, ref);
ah is it because we don't have textValue defined on the individual Tags?

2023-06-14 23:17 UTC, devongovett commented on packages/react-aria-components/src/TagGroup.tsx
> +  let {rowProps, gridCellProps, removeButtonProps, ...states} = useTag({item}, state, ref);
Good catch!

2023-06-14 23:18 UTC, devongovett commented on packages/react-aria-components/src/TagGroup.tsx
> +    }
We should make it consistent with whatever we end up doing for GridList yeah. I'll note that for followup.

2023-06-15 18:24 UTC, reidbarber approved these changes

2023-06-15 21:12 UTC, merged