(wip) Rac dropzone labels
adobe/react-spectrum pull request #4703
Opened 2023-06-23 22:23 UTC by yihuiliao

Closes 

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

## 🧢 Your Project:

2023-07-18 21:41 UTC, ktabors submitted a review, later dismissed

2023-07-18 23:02 UTC, LFDanLu requested changes

2023-07-18 23:02 UTC, LFDanLu commented on packages/react-aria-components/src/DropZone.tsx
>    let labelProps = useLabels({'aria-labelledby': textId});
```suggestion
  let ariaLabel = props['aria-label'] || 'DropZone';
  let labelProps = useLabels({'aria-label': ariaLabel, 'aria-labelledby': textId});
```
and then replace the aria-label below on line 95 with `aria-label={ariaLabel}`

2023-07-18 23:58 UTC, LFDanLu approved these changes

2023-07-19 16:04 UTC, reidbarber approved these changes
LGTM

2023-07-19 17:07 UTC, merged