HCM: fix Link text color
adobe/react-spectrum pull request #4799
Opened 2023-07-20 19:09 UTC by reidbarber

Closes #3981

In High Contrast Mode, Links should have the `LinkText` color for all states.

This includes the assumption that this should apply to the `overBackground` variant as well.

Should not apply to the  `secondary` variant, since it inherits color i.e. `CanvasText`.

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

Test all Link variants in High Contrast Mode against expected colors described above.

## 🧢 Your Project:

2023-07-20 21:29 UTC, yihuiliao approved these changes
lgtm

2023-07-20 21:51 UTC, ktabors submitted a review, later dismissed

2023-07-21 14:40 UTC, majornista commented
I think `[variant="secondary"]` should also use LinkColor in HCM. Particularly with the `isQuiet`, it the link color becomes indistinguishable from static text. The Spectrum specification agrees: 
[<img width="756" alt="Screen shot from Adobe XD for Link-WindowsHighContrast" src="https://github.com/adobe/react-spectrum/assets/154077/7d768963-ba14-4d2a-a8bb-8137cddb667f" />](https://spectrum.adobe.com/static/Windows-High-Contrast-Kits/Link-WindowsHighContrast.xd)

2023-07-21 15:05 UTC, majornista requested changes
variant="secondary" should also use LinkColor.

2023-07-21 16:48 UTC, majornista approved these changes

2023-07-21 20:21 UTC, yihuiliao approved these changes

2023-07-21 21:02 UTC, devongovett approved these changes

2023-07-21 21:13 UTC, merged