Add data-selection-mode attribute
adobe/react-spectrum pull request #5018
Opened 2023-09-02 01:26 UTC by devongovett

Exposes the `selectionMode` render prop as a data attribute. Mainly to fix the Menu selection examples which used to use `aria-checked` to reserve space for the checkmark even when not selected, but this broke after the move to data attributes.

2023-09-02 01:26 UTC, devongovett commented on packages/react-aria-components/src/Menu.tsx
> -}
Now unnecessary - ItemRenderProps already covers this.

2023-09-02 01:31 UTC, devongovett commented on packages/react-aria-components/docs/Table.mdx
> -    }
unused in this example

2023-09-03 21:59 UTC, snowystinger approved these changes

2023-09-05 14:35 UTC, reidbarber requested changes
Can you add this to the tailwind plugin as well?

2023-09-05 17:55 UTC, reidbarber approved these changes
Approving since my comment https://github.com/adobe/react-spectrum/pull/5018#pullrequestreview-1611214752 got handled in #5027

2023-09-05 19:04 UTC, merged