useObjectRef docs
adobe/react-spectrum pull request #5688
Opened 2024-01-11 19:40 UTC by snowystinger

Closes 

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

## 🧢 Your Project:

2024-01-12 15:51 UTC, reidbarber requested changes
One small snit

2024-01-12 15:51 UTC, reidbarber commented on packages/@react-aria/utils/docs/useObjectRef.mdx
> +callback ref or object ref was passed in. This is useful for passing refs to aria hooks.
```suggestion
`useObjectRef` is a utility function that will give an object ref back regardless of if a
callback ref or object ref was passed in. This is useful for passing refs to React Aria hooks.
```

2024-01-12 15:51 UTC, reidbarber commented on packages/@react-aria/utils/docs/useObjectRef.mdx
> +callback ref or object ref was passed in. This is useful for passing refs to aria hooks.
We could also update the JSDocs to mach this. I think it has Hooks capitalized now.

2024-01-23 21:10 UTC, reidbarber approved these changes
LGTM

2024-01-23 22:07 UTC, LFDanLu approved these changes

2024-01-24 00:35 UTC, merged