Add transition to Submenu Tray when moving between levels
adobe/react-spectrum pull request #5984
Opened 2024-03-01 22:01 UTC by reidbarber

Adds a slide in/out transition when navigating between submenu level in the mobile tray experience.

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/WAI/ARIA/apg/)

## 📝 Test Instructions:

Test RSP Submenu stories on mobile.

## 🧢 Your Project:

RSP

2024-03-06 03:38 UTC, ktabors reviewed
Now that we have this nice animation should menu item unavailable also use it?

2024-03-06 03:38 UTC, ktabors commented on packages/@react-spectrum/menu/src/Menu.tsx
> +  }, [hasOpenSubmenu, isSubmenu]);
Why is `isSubmenu` needed? Why is `isSubmenu` a variable that isn't state too?

2024-03-06 22:03 UTC, snowystinger reviewed
When going back up a level, the old menu "snaps" in at the last second. Any way we can fade it in a little? or make it part of the animation and have it slide in from the left? (it could slide out as well when going down a level)

Otherwise, it is a big improvement!

2024-03-14 17:55 UTC, reidbarber commented
@snowystinger just added a transition to the opacity, so that should be improved.

2024-03-18 01:44 UTC, snowystinger submitted a review, later dismissed
lgtm, tested on iOS

2024-04-01 22:46 UTC, LFDanLu commented on packages/@react-spectrum/menu/src/ContextualHelpTrigger.tsx
> +    }, 300); // Matches transition duration
should this be 220 as well?

2024-04-01 23:32 UTC, snowystinger approved these changes

2024-04-02 00:25 UTC, snowystinger requested changes

2024-04-02 00:25 UTC, snowystinger commented on packages/@react-spectrum/menu/src/Menu.tsx
> +    setTimeout(() => {
need to clean this up in the return of a useEffect

2024-04-02 20:46 UTC, snowystinger approved these changes

2024-04-06 00:00 UTC, LFDanLu approved these changes

2024-04-06 00:47 UTC, merged