Export `HiddenContext` from the utils in `react-aria-components`
adobe/react-spectrum pull request #6459
Opened 2024-05-28 11:44 UTC by thexpand

This will give user land components the opportunity to use the context to replace components like the Popover in the Select component without breaking the functionality of the Select.

Closes #6453 

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- N/A ~~Added/updated unit tests and storybook for this change (for new code or code which already has tests).~~
- [x] Filled out test instructions.
- N/A ~~Updated documentation (if it already exists for this component).~~
- [x] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/WAI/ARIA/apg/)

## 📝 Test Instructions:

1. Render a JSX tree using `react-aria-components`:
```tsx
<Select>
  <Label>Favorite Animal</Label>
  <Button>
    <SelectValue />
    <span aria-hidden="true">▼</span>
  </Button>
  <Popover>
    <ListBox>
      <ListBoxItem>Aardvark</ListBoxItem>
      <ListBoxItem>Cat</ListBoxItem>
      <ListBoxItem>Dog</ListBoxItem>
      <ListBoxItem>Kangaroo</ListBoxItem>
      <ListBoxItem>Panda</ListBoxItem>
      <ListBoxItem>Snake</ListBoxItem>
    </ListBox>
  </Popover>
</Select>
```

2. Create a new component to replace the Popover:
```tsx
function PopoverReplacement(props: {  }, ref: ForwardedRef<HTMLElement>) {
  const state = useContext(OverlayTriggerStateContext);
  const isHidden = useContext(HiddenContext);

  if (isHidden) {
    return <>{props.children}</>;
  }

  if (state && !state.isOpen) {
    return null;
  }

  return (
    <div ref={ref}>{props.children}</div>
  );
}

const _PopoverReplacement = /*#__PURE__*/ (forwardRef as forwardRefType)(PopoverReplacement);
export {_PopoverReplacement as PopoverReplacement};
```

3. Render the `PopoverReplacement` instead of the `Popover` in the JSX created in point 1:
```tsx
<Select>
  <Label>Favorite Animal</Label>
  <Button>
    <SelectValue />
    <span aria-hidden="true">▼</span>
  </Button>
  <PopoverReplacement>
    <ListBox>
      <ListBoxItem>Aardvark</ListBoxItem>
      <ListBoxItem>Cat</ListBoxItem>
      <ListBoxItem>Dog</ListBoxItem>
      <ListBoxItem>Kangaroo</ListBoxItem>
      <ListBoxItem>Panda</ListBoxItem>
      <ListBoxItem>Snake</ListBoxItem>
    </ListBox>
  </PopoverReplacement >
</Select>
```

The select should continue to work as usual and have the options pre-populated, even when the popover replacement is not visible yet, e.g. during SSR.

## 🧢 Your Project:

`react-aria-components`

2024-05-28 12:34 UTC, thexpand commented
Looks like there are failing tests but they are not triggered because of the changes in this PR, but by something else.

2024-05-28 14:34 UTC, reidbarber requested changes

2024-05-28 19:26 UTC, thexpand commented on packages/react-aria-components/src/index.ts
> +export {composeRenderProps, DEFAULT_SLOT, Provider, useContextProps, useSlottedContext, HiddenContext } from './utils';
Oh, thanks.. probably just muscle memory.

2024-05-28 19:28 UTC, thexpand commented
@devongovett Exporting `forwardRefType` is not that important in this instance, to be honest. I mean, probably anyone who uses generics in user land code and uses forward ref on the same components would need a similar type to battle TypeScript. We can remove the export of this "hack".

2024-05-31 19:34 UTC, sadeghbarati commented
Please also export other useful functions/components like

- useCollectionDocument
- CollectionDocumentContext
- Hidden 
- removeDataAttributes 
- useRenderProps 
- RenderProps and forwardRefType and RACValidation (types)

2024-06-03 19:55 UTC, thexpand commented
What would be the reason to do so, @sadeghbarati ? My particular use case is to introduce a custom popover component (in place of the one provided by React Aria).

2024-06-03 23:04 UTC, sadeghbarati commented
> What would be the reason to do so

@thexpand https://github.com/adobe/react-spectrum/issues/2140#issuecomment-2083302614

2024-06-03 23:09 UTC, snowystinger commented
Just to be clear, we won't be exporting anything in order to support a multiple selection combobox. It's not an accessible pattern. Let's keep that discussion to that thread, this is a different issue.

2024-06-04 01:05 UTC, devongovett commented
My concern is that it feels very "implementation-detail"-y. I think we want to allow creating custom popovers to work with select/combobox, but as it is, this seems quite difficult to document. Seems like we need a more official API, but I'm not sure what that would be yet.

In the meantime, does it work if you use `display: none` when the popover is closed instead of removing it from the DOM by returning `null`? This would mean that the popover/listbox would always mount, but the browser wouldn't render it. Not totally ideal because of the extra DOM nodes, but does it work as a temporary solution?

2024-06-04 06:27 UTC, thexpand commented
@devongovett Using simply a `display: none` won't work, because I need to render a `ListBox` inside my popover as well. Doing so will render the options twice.

I think we can leave it at just exporting the HiddenContext, as we have other contexts exported as well.

What do you think?

2024-07-12 22:40 UTC, devongovett commented
resolved by #6640

2024-07-12 22:40 UTC, closed without merging